apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: subscribie-onboarding-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01

spec:
  rules:
  - host: test.subscribie.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: subscribie-onboarding-svc
          servicePort: 80
  tls:
  - hosts:
    - test.subscribie.co.uk
    secretName: subscribie-co-uk-wildcard-tls
