kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-create
rules:
  - apiGroups: ["extensions","apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-creator
subjects:
  - kind: ServiceAccount
    name: cronpod
    namespace: default
roleRef:
  kind: ClusterRole
  name: deployments-create
  apiGroup: rbac.authorization.k8s.io

