kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: persistentvolumeclaims-create
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: persistentvolumeclaims-creator
subjects:
  - kind: ServiceAccount
    name: cronpod
    namespace: default
roleRef:
  kind: ClusterRole
  name: persistentvolumeclaims-create
  apiGroup: rbac.authorization.k8s.io

